apiVersion: v1
kind: Pod
metadata:
  name: privpod
  # Note that the Pod does not need to be in the same namespace as the loader.
  labels:
spec:
  containers:
  - name: privpod
    image: 192.168.200.50:5000/alpine-containertools
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /node
      name: noderoot
  volumes:
  - name: noderoot
    hostPath: 
      path: /
